title: Risbuild
email: radoslavsapundzhiev@gmail.com
description: Latest technologies, combined with expert work!
destination: docs
baseurl: "/risbuild" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: radoslavsapundzhiev
github_username:  radoslavsapundzhiev

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
